version: "3"

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insta
    ports:
      - "5432:5432"
