version: "3.9"

services:
  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=insta
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
  insta:
    build: .
    command:
      - serve
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
