// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"database/sql"
)

type Post struct {
	Ident     int64
	Caption   string
	Images    []string
	CreatedAt sql.NullTime
}

type User struct {
	Ident     int64
	Username  string
	Password  string
	CreatedAt sql.NullTime
}
