GRPC http://localhost:8080/post.PostStorage/CreatePost

{
  "post": {
    "caption": "test text",
    "images": [
      "test-image-1",
      "test-image-2"
    ]
  }
}

###
GRPC http://localhost:8080/post.PostStorage/ListPosts

{
  "count": 10,
  "last_item_ident": 0
}